### ISSUE TITLE
Support the new Pixart 2K model

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [city96/ComfyUI_ExtraModels#23]
Pixart just dropped a "2K" model at https://huggingface.co/PixArt-alpha/PixArt-Sigma/tree/main

I tried running it but that one just errors with:

```
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ExtraModels\PixArt\nodes.py", line 29, in load_checkpoint
    model = load_pixart(
            ^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ExtraModels\PixArt\loader.py", line 102, in load_pixart
    m, u = model.diffusion_model.load_state_dict(state_dict, strict=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PixArtMS:
        size mismatch for pos_embed: copying a param with shape torch.Size([1, 16384, 1152]) from checkpoint, the shape in current model is torch.Size([1, 4096, 1152]).
```

**Comment by city96** [comment]
I added the config/resolutions but can't really test rn. Can you check it out?

**Comment by GalaxyTimeMachine** [comment]
Thanks for the fast turnaround! Works perfectly 👍🏻
