### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied (16x1024 and 4096x1152)

### ISSUE THREAD

**Issue by Bigfield77** [city96/ComfyUI_ExtraModels#6]
Hello,

Thanks for bringing pixart to comfyui!

I am trying to use the default workflow and I am getting a  mat1 and mat2 shapes cannot be multiplied (16x1024 and 4096x1152)

I am using PixArt-XL-2-1024x1024.pth 

Here's the full trace:

got prompt
model_type EPS
adm 0
Warning: lewei scale: (2,), base size: 64
Loading T5 from 'D:\stable\comfyUI\ComfyUI\models\t5\ZET5'
Requested to load BaseModel
Loading 1 new model
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\stable\comfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\stable\comfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\stable\comfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\stable\comfyUI\ComfyUI\nodes.py", line 1299, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\stable\comfyUI\ComfyUI\nodes.py", line 1269, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\stable\comfyUI\ComfyUI\comfy\sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\stable\comfyUI\ComfyUI\comfy\samplers.py", line 715, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\stable\comfyUI\ComfyUI\comfy\samplers.py", line 621, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\stable\comfyUI\ComfyUI\comfy\samplers.py", line 560, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\stable\comfyUI\ComfyUI\comfy\k_diffusion\sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable\comfyUI\ComfyUI\comfy\samplers.py", line 284, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable\comfyUI\ComfyUI\comfy\samplers.py", line 274, in forward
    return self.apply_model(*args, **kwargs)
  File "D:\stable\comfyUI\ComfyUI\comfy\samplers.py", line 271, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "D:\stable\comfyUI\ComfyUI\comfy\samplers.py", line 252, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "D:\stable\comfyUI\ComfyUI\comfy\samplers.py", line 226, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\stable\comfyUI\ComfyUI\comfy\model_base.py", line 85, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable\comfyUI\ComfyUI\custom_nodes\ComfyUI_ExtraModels\PixArt\models\PixArtMS.py", line 215, in forward
    out = self.forward_raw(
  File "D:\stable\comfyUI\ComfyUI\custom_nodes\ComfyUI_ExtraModels\PixArt\models\PixArtMS.py", line 169, in forward_raw
    y = self.y_embedder(y, self.training)  # (N, D)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable\comfyUI\ComfyUI\custom_nodes\ComfyUI_ExtraModels\PixArt\models\PixArt_blocks.py", line 399, in forward
    caption = self.y_proj(caption)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable\comfyUI\comf\lib\site-packages\timm\models\layers\mlp.py", line 27, in forward
    x = self.fc1(x)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable\comfyUI\comf\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
R

**Comment by Bigfield77** [comment]
I am running on windows, latest comfy and extension
torch  2.1.1+cu118,  transformers           4.36.0,  bitsandbytes           0.40.1.post1

**Comment by city96** [comment]
The only real guess I have is that you're using the wrong T5 version? It should be [t5v1.1 xxl](https://huggingface.co/DeepFloyd/t5-v1_1-xxl/tree/main).

That or you're using the diffusers version for the PixArt model instead of the one from [here](https://huggingface.co/PixArt-alpha/PixArt-alpha/blob/main/PixArt-XL-2-1024-MS.pth) but that's unlikely since it wouldn't even load...

**Comment by Bigfield77** [comment]
That was it!

I don't know how I took the wrong T5 but I did :)

It was 44gigs, that explains why I thought the t5 loader was slow.. :D  

Thanks for your help!

**Comment by city96** [comment]
No problem! Glad you got it sorted.
