### ISSUE TITLE
I'm getting errors from running it

### ISSUE THREAD

**Issue by Njasa2k** [city96/ComfyUI_ExtraModels#62]
```
11:47:06.416 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
11:47:06.417 [Warning] ComfyUI-0 on port 7821 stderr:   File "C:\Users\*****\Downloads\StableSwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 1890, in load_custom_node
11:47:06.417 [Warning] ComfyUI-0 on port 7821 stderr:     module_spec.loader.exec_module(module)
11:47:06.419 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 936, in exec_module
11:47:06.419 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 1073, in get_code
11:47:06.419 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 1130, in get_data
11:47:06.420 [Warning] ComfyUI-0 on port 7821 stderr: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\*****\\Downloads\\StableSwarmUI\\dlbackend\\comfy\\ComfyUI\\custom_nodes\\custom_nodes\\__init__.py'
```

**Comment by city96** [comment]
To me that looks like the git clone created a subfolder in the custom nodes folder (`custom_nodes\\custom_nodes`) instead of cloning it normally.

The command from the readme assumes you're just in the root ComfyUI folder.
```
git clone https://github.com/city96/ComfyUI_ExtraModels custom_nodes/ComfyUI_ExtraModels
```

If you're in the custom nodes folder already, you can do this instead:
```
git clone https://github.com/city96/ComfyUI_ExtraModels
```
